previews:
  generation: automatic # enable automatic preview generation

services:
  - type: web
    name: mysql-db
    runtime: image
    image:
      url: mysql
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 5
    envVars:
      - fromGroup: mysql

  - type: web
    name: service1
    runtime: image
    image:
      url: kira2308/service1
    envVars:
      - key: DB_HOST
        value: mysql-db

  - type: web
    name: service2
    runtime: image
    image:
      url: kira2308/service2
    envVars:
      - key: DB_HOST
        value: mysql-db

envVarGroups:
  - name: mysql
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: 1234
