spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:test}?useUnicode=true&createDatabaseIfNotExist=true"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:1234}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
server:
  port: 8081
  servlet:
    context-path: /api
